### ISSUE TITLE
Move EGL folder to root

### ISSUE THREAD

**Issue by kotauskas** [McNopper/EGL#11]
The repository root contains the `EGL` folder that contains the actual files and a `README.md` that refers to that folder's `README.txt`. What's the purpose of this structure and can you remove it?

**Comment by McNopper** [comment]
Root folder is the project name and accidently the only folder also is names EGL. Same structure is in the other projects. However, in this case, it looks odd.
@nicebyte Up to you, if u want to chane it.

**Comment by nicebyte** [comment]
Yeah, I always wanted to change it myself but never got around to it. Hopefully I'll have time later this week.

**Comment by McNopper** [comment]
The repo with it's structure is in usage. I do not want to break anything.
